### ISSUE TITLE
Migrations not found.

### ISSUE THREAD

**Issue by jeffngugi** [thomasbird1984/spending-tracker-api#5]
When I run php artisan migrate, only two migrations are running. i.e users and passord resets. According to the routes/api, there seem to be more migrations.
Kindly provide the database/migrations for all.

**Comment by thomasbird1984** [comment]
I never created migrations, this project is still very much under development and I would also say in the very early stages. I can provide you with an sql export of all tables, but won't have time to write migrations for a while, this is something I usually wait to do until a codebase is stable, since changes in the data structure are likely to happen. Comment back if you'd like a copy of the sql export.

**Comment by jeffngugi** [comment]
Thanks for the reply Thomas. 
Yes I'd really appreciate if I get the sql export file. Kindly track it or send me a link to download it

**Comment by thomasbird1984** [comment]
@jeffngugi Here is the database dump https://github.com/thomasbird1984/spending-tracker-api/tree/master/database/raw-sql

**Comment by thomasbird1984** [comment]
If you would be so kind you could fork the repo, write migrations and I'll merge it in so that it will be available for others.

**Comment by jeffngugi** [comment]
Thanks Tom. I'll definitely do that
